AWSTemplateFormatVersion: "2010-09-09"
Resources:
  Network:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: stacks/network.yaml

  Database:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: stacks/database.yaml
      Parameters:
        VpcId: !GetAtt Network.Outputs.VpcId
        PrivateSubnet1Id: !GetAtt Network.Outputs.PrivateSubnet1Id
        PrivateSubnet2Id: !GetAtt Network.Outputs.PrivateSubnet2Id

  LoadBalancer:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: stacks/load-balancer.yaml
      Parameters:
        VpcId: !GetAtt Network.Outputs.VpcId
        PublicSubnet1Id: !GetAtt Network.Outputs.PublicSubnet1Id
        PublicSubnet2Id: !GetAtt Network.Outputs.PublicSubnet2Id

  Monitoring:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: stacks/monitoring.yaml

  Ecs:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: stacks/ecs.yaml
      Parameters:
        VpcId: !GetAtt Network.Outputs.VpcId
        PrivateSubnet1Id: !GetAtt Network.Outputs.PrivateSubnet1Id
        PrivateSubnet2Id: !GetAtt Network.Outputs.PrivateSubnet2Id
        DatabaseEndpointAddress: !GetAtt Database.Outputs.EndpointAddress
        LoadBalancerTargetGroupArn: !GetAtt LoadBalancer.Outputs.TargetGroupArn
        LogGroupName: !GetAtt Monitoring.Outputs.LogGroupName
        AlarmTopicArn: !GetAtt Monitoring.Outputs.AlarmTopicArn

  FileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      FileSystemTags:
        - Key: Name
          Value: mattermost

Outputs:
  MattermostURL:
    Value: !GetAtt LoadBalancer.Outputs.Dns
