AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  VpcId:
    Type: String

  PrivateSubnet1Id:
    Type: String

  PrivateSubnet2Id:
    Type: String

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: RDS security group
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 10.0.0.0/16

  SubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS
      SubnetIds:
        - !Ref PrivateSubnet1Id
        - !Ref PrivateSubnet2Id

  Cluster:
    Type: AWS::RDS::DBCluster
    Properties:
      DatabaseName: mattermost
      DBSubnetGroupName: !Ref SubnetGroup
      Engine: aurora-postgresql
      EngineVersion: 14.9
      Port: 5432
      MasterUsername: mattermost
      MasterUserPassword: mattermost
      ServerlessV2ScalingConfiguration:
        MaxCapacity: 1.0
        MinCapacity: 0.5
      VpcSecurityGroupIds:
        - !Ref SecurityGroup

  Instance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBClusterIdentifier: !Ref Cluster
      DBSubnetGroupName: !Ref SubnetGroup
      DBInstanceClass: db.serverless
      Engine: aurora-postgresql
      PubliclyAccessible: false

Outputs:
  EndpointAddress:
    Value: !GetAtt Cluster.Endpoint.Address
